import type { Config } from "tailwindcss"
import { fontFamily } from "tailwindcss/defaultTheme"

const config = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
	],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    fontFamily: {
      sans: ["var(--font-sans)", ...fontFamily.sans],
    },
    lineHeight: {
      "small-font": "var(--big-line-height)",
      "big-font": "var(--small-line-height)",
    },
    fontSize: {
      "12": ["var(--text-12)", "var(--big-line-height)"],
      "14": ["var(--text-14)", "var(--big-line-height)"],
      "16": ["var(--text-16)", "var(--big-line-height)"],
      "18": ["var(--text-18)", "var(--big-line-height)"],
      "20": ["var(--text-20)", "var(--big-line-height)"],
      "24": ["var(--text-24)", "var(--big-line-height)"],
      "30": ["var(--text-30)", "var(--big-line-height)"],
      "36": ["var(--text-36)", "var(--big-line-height)"],
      "48": ["var(--text-48)", "var(--small-line-height)"],
      "60": ["var(--text-60)", "var(--small-line-height)"],
      "72": ["var(--text-72)", "var(--small-line-height)"],
    },
    margin: {
      "4": "var(--space-4)",
      "8": "var(--space-8)",
      "12": "var(--space-12)",
      "16": "var(--space-16)",
      "24": "var(--space-24)",
      "32": "var(--space-32)",
      "48": "var(--space-48)",
      "64": "var(--space-64)",
      "96": "var(--space-96)",
      "128": "var(--space-128)",
      "192": "var(--space-192)",
      "384": "var(--space-384)",
      "512": "var(--space-512)",
      "640": "var(--space-640)",
      "768": "var(--space-768)",
    },
    padding: {
      "4": "var(--space-4)",
      "8": "var(--space-8)",
      "12": "var(--space-12)",
      "16": "var(--space-16)",
      "24": "var(--space-24)",
      "32": "var(--space-32)",
      "48": "var(--space-48)",
      "64": "var(--space-64)",
      "96": "var(--space-96)",
      "128": "var(--space-128)",
      "192": "var(--space-192)",
      "384": "var(--space-384)",
      "512": "var(--space-512)",
      "640": "var(--space-640)",
      "768": "var(--space-768)",
    },
    width: {
      "4": "var(--space-4)",
      "8": "var(--space-8)",
      "12": "var(--space-12)",
      "16": "var(--space-16)",
      "24": "var(--space-24)",
      "32": "var(--space-32)",
      "48": "var(--space-48)",
      "64": "var(--space-64)",
      "96": "var(--space-96)",
      "128": "var(--space-128)",
      "192": "var(--space-192)",
      "384": "var(--space-384)",
      "512": "var(--space-512)",
      "640": "var(--space-640)",
      "768": "var(--space-768)",
    },
    height: {
      "4": "var(--space-4)",
      "8": "var(--space-8)",
      "12": "var(--space-12)",
      "16": "var(--space-16)",
      "24": "var(--space-24)",
      "32": "var(--space-32)",
      "48": "var(--space-48)",
      "64": "var(--space-64)",
      "96": "var(--space-96)",
      "128": "var(--space-128)",
      "192": "var(--space-192)",
      "384": "var(--space-384)",
      "512": "var(--space-512)",
      "640": "var(--space-640)",
      "768": "var(--space-768)",
    },
    colors: {
      border: "var(--border)",
      input: "hsl(var(--input))",
      ring: "hsl(var(--ring))",
      "neutral-very-light": "#F5F5FA",
      "neutral-light": "#E1E6E8",
      "neutral-slightly-light": "#CDD2DC",
      "neutral": "#B4C3CD",
      "neutral-slightly-dark": "#8791A5",
      "neutral-dark": "#5F6978",
      "neutral-very-dark": "#1E2832",
      "primary-very-light": "#EBF5FF",
      "primary-light": "#AAD2F5",
      "primary-slightly-light": "#5FA0D7",
      "primary": "#2D82C8",
      "primary-slightly-dark": "#2364A0",
      "primary-dark": "#19466E",
      "primary-very-dark": "#0F2837",
      "safe-very-light": "#E6FFFA",
      "safe-slightly-light": "#6ED7D2",
      "safe": "#3CAAA0",
      "safe-slightly-dark": "#289187",
      "safe-dark": "#19645A",
      "safe-very-dark": "#0C4141",
      "warning-very-light": "#FFFAF0",
      "warning-light": "#FAF0D7",
      "warning-slightly-light": "#FAE19B",
      "warning": "#F0C864",
      "warning-slightly-dark": "#C8A53C",
      "warning-dark": "#8C691E",
      "warning-very-dark": "#5A460F",
      "danger-very-light": "#FAE6E6",
      "danger-light": "#F5AAAA",
      "danger-slightly-light": "#E6464",
      "danger": "#DC2D2D",
      "danger-slightly-dark": "#B41E1E",
      "danger-dark": "#871919",
      "danger-very-dark": "#5F1414",
    },
    extends: {
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config

export default config