import type { Config } from "tailwindcss"
import { fontFamily } from "tailwindcss/defaultTheme"

const config = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
	],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        sans: ["var(--font-sans)", ...fontFamily.sans],
      },
      fontSize: {
        "text-12": "var(--text-12)",
        "text-14": "var(--text-14)",
        "text-16": "var(--text-16)",
        "text-18": "var(--text-18)",
        "text-20": "var(--text-20)",
        "text-24": "var(--text-24)",
        "text-30": "var(--text-30)",
        "text-36": "var(--text-36)",
        "text-48": "var(--text-48)",
        "text-60": "var(--text-60)",
        "text-72": "var(--text-72)",
      },
      margin: {
        "margin-4": "var(--space-4)",
        "margin-8": "var(--space-8)",
        "margin-12": "var(--space-12)",
        "margin-16": "var(--space-16)",
        "margin-24": "var(--space-24)",
        "margin-32": "var(--space-32)",
        "margin-48": "var(--space-48)",
        "margin-64": "var(--space-64)",
        "margin-96": "var(--space-96)",
        "margin-128": "var(--space-128)",
        "margin-192": "var(--space-192)",
        "margin-384": "var(--space-384)",
        "margin-512": "var(--space-512)",
        "margin-640": "var(--space-640)",
        "margin-768": "var(--space-768)",
      },
      padding: {
        "padding-4": "var(--space-4)",
        "padding-8": "var(--space-8)",
        "padding-12": "var(--space-12)",
        "padding-16": "var(--space-16)",
        "padding-24": "var(--space-24)",
        "padding-32": "var(--space-32)",
        "padding-48": "var(--space-48)",
        "padding-64": "var(--space-64)",
        "padding-96": "var(--space-96)",
        "padding-128": "var(--space-128)",
        "padding-192": "var(--space-192)",
        "padding-384": "var(--space-384)",
        "padding-512": "var(--space-512)",
        "padding-640": "var(--space-640)",
        "padding-768": "var(--space-768)",
      },
      width: {
        "width-4": "var(--space-4)",
        "width-8": "var(--space-8)",
        "width-12": "var(--space-12)",
        "width-16": "var(--space-16)",
        "width-24": "var(--space-24)",
        "width-32": "var(--space-32)",
        "width-48": "var(--space-48)",
        "width-64": "var(--space-64)",
        "width-96": "var(--space-96)",
        "width-128": "var(--space-128)",
        "width-192": "var(--space-192)",
        "width-384": "var(--space-384)",
        "width-512": "var(--space-512)",
        "width-640": "var(--space-640)",
        "width-768": "var(--space-768)",
      },
      height: {
        "height-4": "var(--space-4)",
        "height-8": "var(--space-8)",
        "height-12": "var(--space-12)",
        "height-16": "var(--space-16)",
        "height-24": "var(--space-24)",
        "height-32": "var(--space-32)",
        "height-48": "var(--space-48)",
        "height-64": "var(--space-64)",
        "height-96": "var(--space-96)",
        "height-128": "var(--space-128)",
        "height-192": "var(--space-192)",
        "height-384": "var(--space-384)",
        "height-512": "var(--space-512)",
        "height-640": "var(--space-640)",
        "height-768": "var(--space-768)",
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--neutral-very-light))",
        foreground: "hsl(var(--neutral-very-dark))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-very-dark))",
        },
        secondary: {
          DEFAULT: "hsl(var(--neutral))",
          foreground: "hsl(var(--neutral-very-dark))",
        },
        destructive: {
          DEFAULT: "hsl(var(--danger))",
          foreground: "hsl(var(--danger-very-dark))",
        },
        muted: {
          DEFAULT: "hsl(var(--neutral-slightly-dark))",
          foreground: "hsl(var(--neutral-very-dark))",
        },
        safe: {
          DEFAULT: "hsl(var(--safe))",
          foreground: "hsl(var(--safe-very-dark))",
        },
        popover: {
          DEFAULT: "hsl(var(--neutral-light))",
          foreground: "hsl(var(--neutral-very-dark))",
        },
        card: {
          DEFAULT: "hsl(var(--neutral-light))",
          foreground: "hsl(var(--neutral-very-dark))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config

export default config