name: lint

on:
    push:
        branches: [ main ]
        paths:
            - '*/**/*.tsx'
            - '*/**/*.ts'
    pull_request:
        branches: [ main ]
        paths:
            - '*/**/*.tsx'
            - '*/**/*.ts'

env:
    NODE_VERSION: 19.x

jobs:
    lint:
        runs-on: [ ubuntu-latest ]
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v4
              with:
                node-version: ${{ env.NODE_VERSION }}
            - name: Get yarn
              run: npm i -g yarn
            - name: Get yarn cache directory path
              id: yarn-cache-dir
              run: echo "CACHE_DIR=$(yarn cache dir)" >> $GITHUB_OUTPUT
            - name: cache node modules
              uses: actions/cache@v3
              env:
                cache-name: cache-node-modules
              with:
                path: ${{ steps.yarn-cache-dir.outputs.CACHE_DIR }}
                key: ${{ runner.os }}-yarn-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                    ${{ runner.os }}-yarn-${{ env.cache-name }}-
                    ${{ runner.os }}-yarn-
                    ${{ runner.os }}-
            - name: Install dependencies (no build)
              run: yarn install
            - name: Lint
              run: yarn lint