name: test

on:
    push:
        branches: [ main ]
        paths:
            - '*/**/*.tsx'
            - '*/**/*.ts'
    pull_request:
        branches: [ main ]
        paths:
            - '*/**/*.tsx'
            - '*/**/*.ts'
jobs:
    test:
        runs-on: [ ubuntu-latest ]
        strategy:
            matrix:
                node-version: [17.x, 18.x, 19.x]
        steps:
            - uses: actions/checkout@v3 
            - name: Setup Node version ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}
            - name: Get yarn
              run: npm i -g yarn
            - name: Get yarn cache directory path
              id: yarn-cache-dir
              run: yarn cache dir >> $GITHUB_OUTPUT
            - name: cache node modules
              uses: actions/cache@v3
              env:
                cache-name: cache-node-modules
              with:
                path: ${{ join(steps.yarn-cache-dir.outputs.*, '') }}
                key: ${{ runner.os }}-yarn-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                    ${{ runner.os }}-yarn-${{ env.cache-name }}-
                    ${{ runner.os }}-yarn-
                    ${{ runner.os }}-
            - name: Build with Node ${{ matrix.node-version }}
              run: yarn
            - name: Test
              run: yarn test